### ISSUE TITLE
Crash on select anime

### ISSUE THREAD

**Issue by Yannis-Alouache** [CatAnnaDev/neko_sama_downloader#1]

**Comment by CatAnnaDev** [comment]
have you download chrome driver && chrome brower && ffmpeg as requested ?
or juste update chome browser ?

**Comment by CatAnnaDev** [comment]
if you are on windows you can download this and place chromedriver.exe in utils folder 
https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win64/chromedriver-win64.zip

same for ffmpeg you can download this and place ffmpeg.exe in utils forlder
https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z 
ffmpeg is placed in bin directory

ituls folder may look like this 
![image](https://github.com/CatAnnaDev/neko_sama_downloader/assets/45910905/5a7974cd-f83e-467b-be6a-9d9702a50606)
