### ISSUE TITLE
cmd args not applied

### ISSUE THREAD

**Issue by Pajul7** [CatAnnaDev/neko_sama_downloader#2]
It seems that all or part of the possible options like --ignore, --thread, --save-path and maybe others are not working.
for instance, --tread is recognized (requires a number after it), but it doesn't seem to do much.

![Copie d'écran_20240812_154127](https://github.com/user-attachments/assets/e55d786f-ed44-4be9-b516-526ccb7f5063)

Maybe I'm doing something wrong (possible).
Outside of that, very cool project !

In case it's relevant I'm using an up-to-date Arch Linux 
(do not take this as a flex like 'I use Arch btw', it's just for context)

**Comment by CatAnnaDev** [comment]
you need use the bypass config file arg with -o otherwise neko_dl gonna use config file generated all the time

**Comment by CatAnnaDev** [comment]
it should give
./neko_dl -o -l vostfr -t 2 -a /home/xx/anime -s death parade

yeah if you skip config file you need re-give all arg actually so langue, thread, path

**Comment by CatAnnaDev** [comment]
fixed in new release 0.15.3
