### ISSUE TITLE
Application crash when you select an anime (Win10)

### ISSUE THREAD

**Issue by coolfarmer** [CatAnnaDev/neko_sama_downloader#3]
Hi,

I’m currently experiencing an issue with your application that seems similar to a previous problem you addressed.

I’m using Windows 10. After initiating Neko, it automatically created a config file at `C:/Users/Skullprior-PC/AppData/Roaming/config.json`

The content of the file is:
`{"language":"vf","thread":10,"save_path":"C:/Users/Skullprior-PC/Desktop/AnimeFilesTmp"}`

I downloaded your Windows release into this folder:
`C:/Users/Skullprior-PC/Desktop/neko`

As you mentioned, I updated my Chrome browser to the latest version (128.0.6613.85). I also downloaded FFMpeg using the link you provided in the previous issue and downloaded chromedriver from this link: https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.85/win64/chromedriver-win64.zip

My `neko` folder now looks like this:
```
C:/Users/Skullprior-PC/Desktop/neko
├── neko_dl.exe
├── utils
├──── chromedriver.exe
└──── ffmpeg.exe
```

I’ve tried various methods for writing paths and configuring folders, but unfortunately, the application continues to crash without any error when I select an anime.

Any help would be greatly appreciated. :)
Thanks!

**Comment by CatAnnaDev** [comment]
Hi, so after a few check yeah it's fully bugged on windows actually, i gonna fix it soon, but for now i've found a lil fix for some crash

after any try you need to kill all chrome process stayed open by neko_dl ( chromiumoxide for real ) when all process are killed now it work fine BUT ffmpeg are broken too so i'll fix it soon

**Comment by CatAnnaDev** [comment]
so i've try a bit with this version and all work fine 
https://github.com/CatAnnaDev/neko_sama_downloader/releases/tag/0.15.4.1

let me know if you've another problem otherwise you can use tag -v when you start neko_dl for more verbose data and know when it crash && you can delete chromedriver but keep ffmpeg and normally thats work like that, i don't use windows atm so i can't test it correctly

**Comment by coolfarmer** [comment]
Thanks for your reply!

With version 0.15.4.1, it seems that the application takes a bit longer before crashing (about 1 or 2 more seconds). However, the same crash still occurs.

Right after I select an anime, the app asks which season I want, it crashes a second later.

Here is a screenshot just before the crash:
![2024-08-24_20-16-17](https://github.com/user-attachments/assets/d58ae371-d2ed-4a5c-a5fe-612cc97f9fc9)

**Comment by CatAnnaDev** [comment]
try to kill all chrome instance with the task manager then retry, normally it work like that

with chormiumoxide, when the app chrash it let all chromeprocess open and windows keep it as orphan
 process, so it crash after that so yeah try like that and tell me if it's okay or not i can't do nothing actually for that

**Comment by CatAnnaDev** [comment]
hum have you press space key to select your anime ? windows terminal dosen't show the green check mark when it's okay but with your screen i don't see Process step 1/X

when you move with directional arrow press space key to " select " this anime and add it to the queue to process when all is done press enter to start

**Comment by CatAnnaDev** [comment]
https://github.com/user-attachments/assets/c47ae0cd-12da-4eca-831c-046ce28fdf67
